### PR TITLE
make config and metadata visible

### LINKED ISSUE #21: need to track OCI image source info
I want to be able to say which mounted OCI image has corrupted layers when checking with `atomfs verify` (see #20) or via some other mechanism that gets notified that a device is corrupt.

The molecule should keep track of the OCI image path that it was created from, and we should be able to trace from a device name to a list of molecules and OCI images that are affected.

since the current molecule metadata is overmounted, maybe atomfs lib should maintain a separate directory with this info:
```
atomfsmeta/
atomfsmeta/50bd5ba895c-verity/
atomfsmeta/50bd5ba895c-verity/$ocilayoutpath/$tagname1
atomfsmeta/50bd5ba895c-verity/$ocilayoutpath2/$tagname2
etc...
```
seeing as how this is tied to the verity implementation, possibly this should be an implementation detail of `atomfs verify` and that command could just output OCI tag info. but we do need to make it available somewhere.

### PR DESCRIPTION
**Pull request by mikemccracken**
"write molecule config to metadata path" is important to be able to trace an event that points at a failed DM Verity volume, through its molecule mountpoint, to an OCI image and potentially to a container running that image that we then need to stop.

"move metadata path to /run" is handy for testing, but is not strictly required, since it only changes the behavior of the `atomfs` binary. Other programs using atomfs as a package are free to set the metadata path however they want, if they need it to be accessible while the molecule is mounted.

Fixes #21

### CODE REVIEW

**Comment by hallyn** [comment]
> Error: cmd/atomfs/umount.go:10:2: "machinerun.io/atomfs/log" imported and not used

**Comment by hallyn** [comment]
Otherwise looks fine to me, thanks

**Comment by mikemccracken** [comment]
derp! thanks, fixed

**Comment by mikemccracken** [comment]
thanks for the review, I was wondering if there was a reason to object to moving away from the nice neat tucked-under-the-mountpoint approach. I didn't look *too* hard but didn't think of a nice way to get at the meta of a still-mounted molecule with the previous scheme..

**Comment by hallyn** [comment]
Well, now that you mention it, there *is* reason :)  If different users (or different root logins) each try to mount to the same mountpoint in different namespaces, which is perfectly legitimate, then there will now be conflicts, right?

**Comment by mikemccracken** [comment]
that's a good point, do you have a scheme in mind that fixes that? Is there a way to get a unique string that maps to a given mount namespace?

Or alternately maybe we should keep the old behavior as default and add a `--use-central-meta` flag (bad name) that does what I added here?

**Comment by hallyn** [comment]
Yeah, you should be able to use:
```
serge@honeybadger:~$ ls -l /proc/self/ns/mnt
lrwxrwxrwx 1 serge serge 0 Oct  2 13:39 /proc/self/ns/mnt -> 'mnt:[4026531841]'
```
For the mounter.  That mntns name will be unique as long as that mntns exists, so if it created the mount, it'll live as long as the mount does.

**Comment by mikemccracken** [comment]
closing this for a new PR with this change but also more. My earlier assertion that "Other programs using atomfs as a package are free to set the metadata path however they want, if they need it to be accessible while the molecule is mounted." may have been true but it meant duplicating a lot of atomfs code in those programs, so my new PR has a different approach where the mount code moves into the atomfs package and everything using it to mount a molecule will get the metadata at `/run/atomfs/meta`. It will incorporate the suggestion to use the mount nsname.

**Pull request closed without merging**
